# Generated by Django 3.2.4 on 2021-06-22 06:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(blank=True, max_length=50, null=True)),
                ('course_code', models.CharField(blank=True, max_length=30, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_name', models.CharField(blank=True, max_length=30, null=True)),
                ('teacher_id', models.IntegerField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('ft', 'Full-Time'), ('pt', 'Part-Time')], default='ft', max_length=10, null=True)),
                ('contact', models.CharField(blank=True, max_length=50, null=True)),
                ('subject_ids', models.ManyToManyField(blank=True, related_name='subject_teacher', to='cuscal.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(blank=True, max_length=30, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('subject_ids', models.ManyToManyField(blank=True, related_name='subject_student', to='cuscal.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('active', models.BooleanField(blank=True, default=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('update', models.DateTimeField(auto_now=True, null=True)),
                ('review_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('teacher_ids', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_review', to='cuscal.teacher')),
            ],
        ),
    ]
