# Generated by Django 3.2.4 on 2021-06-23 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuscal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='teacher',
            name='number_rating',
            field=models.IntegerField(default=0),
        ),
    ]
